baseurl = "https://blog.r-project.org"
languageCode = "en-us"
title = "The R Blog"
relativeURLs = false
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$","_cache$",
               "\\.knit\\.md$", "\\.utf8\\.md$"]

# https://github.com/rstudio/blogdown/issues/447
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/index.html"

[params]
    description = "R Blog"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "Rlogo.png"
    width = 100
    height = 78
    alt = "R"

